# Generated by Django 2.2 on 2020-01-26 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_auto_20200126_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='cvv',
            new_name='CVV',
        ),
    ]
