# Generated by Django 2.2 on 2020-01-26 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0003_auto_20200126_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='expiry',
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
